- README.md
- backend/main.py
- backend/pyproject.toml
- backend/requirements.txt
- backend/settings.yaml
- backend/streams_explorer/core/config.py
- backend/streams_explorer/core/extractor/extractor_container.py
- backend/streams_explorer/default.py
- backend/streams_explorer/streams_explorer.py
- backend/tests/test_application.py
> Update graph automatically

- grafana/consumer-groups.json
- grafana/topics.json
> Add Grafana dashboards

- README.md
- backend/settings.yaml
- backend/streams_explorer/core/config.py
- backend/streams_explorer/defaultlinker.py
- backend/tests/test_linker.py
- backend/tests/test_streams_explorer.py
- backend/tests/utils.py
> Link to consumer groups Grafana dashboard

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/DashedEdge.tsx
- frontend/src/components/GraphVisualization.test.tsx
- frontend/src/components/GraphVisualization.tsx
- frontend/src/setupTests.ts
> Add edge animation to highlight activity in pipelines

- backend/streams_explorer/core/extractor/default/elasticsearch_sink.py
- backend/streams_explorer/core/extractor/default/jdbc_sink.py
- backend/streams_explorer/core/extractor/default/s3_sink.py
- backend/streams_explorer/extractors.py
- backend/tests/test_application.py
- backend/tests/test_extractors.py
- frontend/public/jdbc-sink.svg
- frontend/public/s3-bucket.svg
> Add extractors for Amazon S3 & JDBC sink connectors

- backend/requirements.txt
- backend/streams_explorer/core/services/kafkaconnect.py
- backend/streams_explorer/streams_explorer.py
- backend/tests/test_kafka_connect.py
- backend/tests/test_streams_explorer.py
> Sanitize Kafka Connect config secrets

- backend/streams_explorer/core/extractor/default/elasticsearch_sink.py
- backend/streams_explorer/core/extractor/default/generic.py
- backend/streams_explorer/core/extractor/default/jdbc_sink.py
- backend/streams_explorer/core/extractor/default/s3_sink.py
- backend/streams_explorer/core/extractor/extractor.py
- backend/streams_explorer/core/extractor/extractor_container.py
- backend/streams_explorer/core/services/dataflow_graph.py
- backend/streams_explorer/core/services/kafkaconnect.py
- backend/streams_explorer/extractors.py
- backend/streams_explorer/models/kafka_connector.py
- backend/tests/test_dataflow_graph.py
- backend/tests/test_extractors.py
- backend/tests/test_streams_explorer.py
> Visualize Kafka Connect dead letter topics & Add generic Extractors

- backend/streams_explorer/core/services/metric_providers.py
- backend/streams_explorer/models/graph.py
- backend/tests/test_metricprovider.py
- backend/tests/test_metricprovider_data.py
- frontend/src/App.tsx
- frontend/src/api/fetchers.tsx
- frontend/src/components/GraphVisualization.tsx
> Display number of Connector tasks as metric

- frontend/src/components/GraphVisualization.test.tsx
- frontend/src/components/GraphVisualization.tsx
> Improvements to animated edges in graph

- frontend/src/App.tsx
- frontend/src/components/GraphVisualization.tsx
- frontend/src/graphConfiguration.ts
Closes #53 
Menu alignment options sadly aren't implemented in ant.design https://github.com/ant-design/ant-design/issues/10749
> Search and focus nodes

- README.md
- backend/streams_explorer/core/services/dataflow_graph.py
- backend/streams_explorer/default.py
- backend/streams_explorer/linker.py
- backend/streams_explorer/metric_provider.py
- backend/streams_explorer/streams_explorer.py
- backend/tests/test_dataflow_graph.py
- backend/tests/test_metricprovider.py
- backend/tests/test_streams_explorer.py
> Provide MetricProvider as a plugin

- backend/streams_explorer/core/k8s_app.py
- backend/streams_explorer/core/services/dataflow_graph.py
- backend/streams_explorer/core/services/metric_providers.py
- backend/streams_explorer/extractors.py
- backend/streams_explorer/py.typed
- backend/streams_explorer/streams_explorer.py
- backend/tests/test_metricprovider.py
Fixed all warnings reported by pyright, which mypy doesn't detect
> Fix typing warnings

- backend/streams_explorer/core/k8s_app.py
- backend/tests/test_k8s_app.py
- backend/tests/utils.py
> Fix streams app classification false positives

- frontend/package-lock.json
- frontend/package.json
- frontend/src/api/fetchers.tsx
- frontend/src/components/__snapshots__/Details.test.tsx.snap
> Audit npm dependencies

- backend/streams_explorer/core/services/linking_services.py
- backend/streams_explorer/core/services/schemaregistry.py
- backend/streams_explorer/streams_explorer.py
- backend/tests/test_streams_explorer.py
> Fix topic info when schema is unavailable

- frontend/src/components/GraphVisualization.test.tsx
- frontend/src/components/GraphVisualization.tsx
> Fix connector without read rate displayed as active

- backend/streams_explorer/core/services/metric_providers.py
- backend/streams_explorer/models/graph.py
- backend/tests/test_metricprovider.py
- backend/tests/test_metricprovider_data.py
- frontend/public/index.html
- frontend/src/api/fetchers.tsx
- frontend/src/components/GraphVisualization.test.tsx
- frontend/src/components/GraphVisualization.tsx
Closes #102
Show available replica count in addition to desired replica count metric
> Display available replica count

- .pre-commit-config.yaml
- azure-pipelines.yml
- backend/.mypy.ini
- backend/requirements.txt
- backend/streams_explorer/core/k8s_app.py
- backend/streams_explorer/core/services/linking_services.py
- backend/streams_explorer/defaultlinker.py
- backend/tests/test_streams_explorer.py
- frontend/package-lock.json
- frontend/package.json
- frontend/src/api/fetchers.tsx
Closes #108
minor QOL change:
mypy (Python type checker) released a big new version which I updated to. In the course of this I added a pre-commit hook so that it doesn't need to be run manually anymore. Also the CI is checking it for us now which is nice.
> Set up link to AKHQ for consumer group

- backend/.mypy.ini
- backend/streams_explorer/core/k8s_app.py
- backend/streams_explorer/core/services/dataflow_graph.py
- backend/tests/test_dataflow_graph.py
- backend/tests/test_streams_explorer.py
- backend/tests/utils.py
> Improve pipeline assignment for sinks/sources

- README.md
- backend/settings.yaml
- backend/streams_explorer/defaultlinker.py
- backend/tests/test_linker.py
- backend/tests/test_streams_explorer.py
> Link to AKHQ connector tasks

- README.md
- backend/main.py
- backend/settings.yaml
- backend/streams_explorer/core/config.py
- backend/streams_explorer/core/services/dataflow_graph.py
- backend/tests/test_application.py
- backend/tests/test_dataflow_graph.py
> Make distance between pipeline graphs configurable

- backend/requirements.txt
- backend/streams_explorer/api/routes/metrics.py
- backend/streams_explorer/core/services/dataflow_graph.py
- backend/streams_explorer/core/services/metric_providers.py
- backend/streams_explorer/streams_explorer.py
- backend/tests/test_metricprovider.py
> Refactor metrics transformation & make endpoint non-blocking

- backend/main.py
- backend/streams_explorer/api/routes/graph.py
- backend/streams_explorer/api/routes/update.py
- backend/streams_explorer/core/services/dataflow_graph.py
- backend/streams_explorer/streams_explorer.py
- backend/tests/test_dataflow_graph.py
- backend/tests/test_streams_explorer.py
> Cache pipeline graphs & pre-calculate main graph

- frontend/src/App.test.tsx
- frontend/src/App.tsx
> Persist metrics refresh interval & respect "off" setting on load

- backend/streams_explorer/core/services/metric_providers.py
- backend/tests/test_metricprovider.py
- frontend/src/App.tsx
> Throttle frequency of metric updates server-side

- backend/streams_explorer/api/routes/graph.py
- backend/streams_explorer/api/routes/kubernetes_health.py
- backend/streams_explorer/api/routes/metrics.py
- backend/streams_explorer/api/routes/node.py
- backend/streams_explorer/api/routes/pipelines.py
- frontend/src/App.tsx
- frontend/src/api/fetchers.tsx
- frontend/src/components/Details.test.tsx
- frontend/src/components/Details.tsx
> Rename endpoint methods

- backend/streams_explorer/core/services/kafka.py
- backend/streams_explorer/streams_explorer.py
- backend/tests/test_kafka.py
- backend/tests/test_streams_explorer.py
> Display Kafka topic partition count

- backend/poetry.lock
- backend/pyproject.toml
- backend/settings.yaml
- backend/streams_explorer/core/config.py
- backend/streams_explorer/streams_explorer.py
- backend/tests/test_streams_explorer.py
> Cache node info endpoint

- frontend/src/App.test.tsx
- frontend/src/App.tsx
- frontend/src/__snapshots__/App.test.tsx.snap
- frontend/src/components/Details.test.tsx
- frontend/src/components/Details.tsx
- frontend/src/components/DetailsCard.test.tsx
- frontend/src/components/DetailsCard.tsx
- frontend/src/components/GraphVisualization.test.tsx
- frontend/src/components/GraphVisualization.tsx
- frontend/src/components/Node.tsx
- frontend/src/components/Schema.tsx
nodes use display label, ids are used internally only
> Refactor frontend to show node display names

- frontend/src/components/DetailsCard.test.tsx
This was causing Jest to complain occasionally
> Fix missing mock in test

- frontend/src/App.tsx
> Prevent page reload when clicking menu item

- .github/workflows/release.yml
- backend/pyproject.toml
Fix creating and pushing tag in CI
```
Run git tag v1.6.1
fatal: could not read Username for 'https://github.com': No such device or address
Error: Process completed with exit code 128.
```
https://github.com/bakdata/streams-explorer/actions/runs/2422011200
> Fix pushing release tag

- .github/workflows/ci.yml
- backend/poetry.lock
- backend/pyproject.toml
requires Azure agent to be updated
> Test against Python 3.10

- .github/workflows/ci.yml
> Update Docker actions

- backend/README.md
- backend/settings.yaml
- backend/streams_explorer/core/config.py
- backend/streams_explorer/defaultlinker.py
- backend/tests/test_linker.py
- backend/tests/test_streams_explorer.py
> Rename Kowl to Redpanda Console

- .github/workflows/ci.yml
- backend/streams_explorer/core/extractor/default/elasticsearch_sink.py
- backend/streams_explorer/core/extractor/default/generic.py
- backend/streams_explorer/core/extractor/default/jdbc_sink.py
- backend/streams_explorer/core/extractor/default/s3_sink.py
- backend/streams_explorer/core/extractor/extractor.py
- backend/streams_explorer/core/extractor/extractor_container.py
- backend/streams_explorer/core/k8s_config_parser.py
- backend/streams_explorer/core/services/dataflow_graph.py
- backend/streams_explorer/core/services/linking_services.py
- backend/streams_explorer/core/services/metric_providers.py
- backend/streams_explorer/defaultlinker.py
- backend/streams_explorer/extractors.py
- backend/streams_explorer/k8s_config_parser.py
- backend/streams_explorer/linker.py
- backend/streams_explorer/plugins.py
- backend/streams_explorer/streams_explorer.py
- backend/tests/test_extractors.py
- backend/tests/test_kafka_connect_transformer_sink.py
- backend/tests/test_linker.py
- backend/tests/test_metricprovider.py
- backend/tests/test_streams_explorer.py
- fix JDBC & S3 sinks not being cleared upon refresh
- more robust plugin loading
- detect defining class inside plugin module (using `inspect` instead of `dir`)
- handle multiple inheritance
- create abstract base class for all supported plugin types
- create base classes for individual plugin types
- divide Extractor in separate classes to improve usability
nice little added bonus: for the first time Pyright doesn't show any diagnostics whatsoever (including hints)
> Refactor plugin system

- Dockerfile
- backend/README.md
- docker-compose.yaml
- helm-chart/values.yaml
> Change default port to 8080

- backend/streams_explorer/core/k8s_config_parser.py
- backend/tests/test_k8s_app.py
> Parse extra topic roles as list

- backend/streams_explorer/core/services/kubernetes.py
> Fix asyncio tasks reference to prevent GC

- backend/streams_explorer/core/extractor/default/redis_sink.py
- backend/streams_explorer/extractors.py
- backend/tests/test_extractors.py
> Create plugin for Redis sink connector

- .github/workflows/ci.yml
- backend/setup.cfg
debugpy doesn't support running pytest with coverage
> Fix local debugging with debugpy

- backend/streams_explorer/core/k8s_config_parser.py
- backend/streams_explorer/core/services/dataflow_graph.py
- backend/streams_explorer/core/services/kubernetes.py
- backend/streams_explorer/streams_explorer.py
- backend/tests/test_application.py
- backend/tests/test_dataflow_graph.py
- backend/tests/test_streams_explorer.py
- backend/tests/utils.py
> Namespace application nodes
